#! /bin/sh

DAEMON="weston"
DAEMON_EXE="/usr/bin/${DAEMON}"
PIDFILE="/run/${DAEMON}.pid"

export LANG=en_US.UTF-8

# Start Weston from root console (plug USB mouse/keyboard first)
if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi

start() {
	# Workarround HDMI
	hdmi=$(ls -1 /sys/class/drm/card[0-9]-HDMI-A-1/status);
	echo "off" > $hdmi
	echo "on" > $hdmi

	printf 'Starting %s: ' "${DAEMON}"
	start-stop-daemon -S -x "${DAEMON_EXE}" -p "${PIDFILE}" -m -b -- --idle-time=0 --continue-without-input
	status=$?
	if [ "$status" -eq 0 ]; then
		echo OK
	else
		echo FAIL
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "${DAEMON}"
	start-stop-daemon -K -x "${DAEMON_EXE}" -p "${PIDFILE}"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo OK
	else
		echo FAIL
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "${1}" in
	start|stop|restart)
		"${1}";;
	reload)
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
