#! /bin/sh

DAEMON="wayfire"
DAEMON_EXE="/usr/bin/${DAEMON}"
PIDFILE="/run/${DAEMON}.pid"

export LANG=en_US.UTF-8
HOME=/home/wayfire
MY_UID=$(id -u wayfire)

# Use HDMI display only (not ssd13x) for wlroots compositor
hdmi_card_name=$(basename $(find /sys/class/drm -name "card*-HDMI*") | sed -e 's/-.*//')
export WLR_DRM_DEVICES=/dev/dri/$hdmi_card_name

# Allow to start without mouse/keyboard
export WLR_LIBINPUT_NO_DEVICES=1

# Start Wayfire from root console
if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${MY_UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
	(cd /tmp; ln -s 101-runtime-dir/wayfire-wayland-1-.socket wayfire-wayland-1.socket)
	chown -R wayfire:wayfire "${XDG_RUNTIME_DIR}"
    fi
fi

start() {
	# Workarround HDMI
	hdmi=$(ls -1 /sys/class/drm/card[0-9]-HDMI-A-1/status);
	echo "off" > $hdmi
	echo "on" > $hdmi

	printf 'Starting %s: ' "${DAEMON}"
	start-stop-daemon -c wayfire -S -x "${DAEMON_EXE}" -p "${PIDFILE}" -m -b -- --debug
	status=$?
	if [ "$status" -eq 0 ]; then
		echo OK
	else
		echo FAIL
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "${DAEMON}"
	start-stop-daemon -K -x "${DAEMON_EXE}" -p "${PIDFILE}"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo OK
	else
		echo FAIL
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "${1}" in
	start|stop|restart)
		"${1}";;
	reload)
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
